### ISSUE TITLE
Confusion Building Project

### ISSUE THREAD

**Issue by thx1766** [tikimcfee/LookAtThat#5]
Hi :)

I cloned LookAtThat, and noticed that it didn't run out of the box. I changed the development team, and concluded that I needed to do something with MetalLink and BitHandling, so I added them as package dependencies. However, I don't think I'm building and linking the libraries properly - the error I'm stuck on is references to ForceLayoutNode and ForceLayoutEdge.

Any suggestions?

**Comment by tikimcfee** [comment]
Hey there @thx1766 ! I appreciate you dropping by and trying this out!

Off the bat, apologies for not having this in a reasonable state. Suffice it to say, code is hard, yes?

However, I come with good news: `master` is now live with the latest, and most importantly, most buildingest. I'd recommend if you've made a lot of trials at getting it to run with local changes, just trashing your current local build. That goes for anyone reading this, actually. 

The whole project structure has changed to support a more modular setup, for lots of reasons including trying out some separate LSP work. The good part of that is you should be able to give it a run!

The latest version loses syntax highlighting and search at the moment, since I've just wired up the new rendering flow that brings down memory usage and render time down to just a couple of seconds when loading up the entire set of project files - about 250+, and most of that time is me still having a bad layout implementation.

Also, I've finally set up some build testing, so if you're interesting in getting some iOS / iPad app test flight builds as I go, let me know =)

Do let me know if things work or don't, and I'm happy to help!

**Comment by rapidlugo** [comment]
Working on more builds. `master` still works, and some more will be merged in soon to create a fresh TestFlight build. I'll close this out for now, and let me know if you have any other issues!
